import type { Metadata } from 'next'
import FootballNavbar from './FootballNavbar'
import Footer from './Footer'

export const metadata: Metadata = {
    title: 'Premier League - Football',
    description: 'Generated by Premier League',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className='h-full'>
            <FootballNavbar />
            <div className='h-full'>
                {children}
            </div>
            <Footer />
        </div>
    )
}
