import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import LeftSidebar from '@/components/apps-components/LeftSidebar';
import { HiMenuAlt2 } from "react-icons/hi";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font--Poppins"
})

export const metadata: Metadata = {
  title: 'Premier League',
  description: 'Generated by Premier League',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex flex-col lg:flex-row h-screen overflow-auto text-white">
          {/* this is left side bar  */}
          <div className='hidden lg:block lg:w-[4%] 2xl:w-[5%] h-full overflow-auto bg-black'>
            <LeftSidebar />
          </div>

          {/* this div for mobile only  */}
          <div className='lg:hidden w-full py-1 bg-bgBlack text-white'>
            <Sheet>
              <div className='w-full flex items-center text-center px-4 pt-1'>
                <SheetTrigger asChild className='w-[5%] text-lg bg-bgBlack text-white'>
                  <HiMenuAlt2 />
                </SheetTrigger>
                <h3 className='text-center font-medium w-[95%]'>Premier League</h3>
              </div>
              <SheetContent side={"left"} className='w-1/4 bg-bgBlack text-white p-0 m-0 pt-10'>
                <LeftSidebar />
              </SheetContent>
            </Sheet>
          </div>

          {/* this is right side  */}
          <div className='w-full lg:w-[96%] 2xl:w-[95%] bg-bgBlack h-full overflow-auto'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
